import { NativeModules } from 'react-native';
import {
	AdMobBanner,
	AdMobInterstitial,
	PublisherBanner,
	AdMobRewarded,
} from 'react-native-admob';

global.mainColor = "#343434";
global.PROTOCOL = "http";
global.HOST = "apps.n29itech.xyz";
//global.HOST = "192.168.43.254";
global.API_URL = PROTOCOL+"://"+HOST+"/tafsir_mimpi";
global.USERDATA_URL = PROTOCOL+"://"+HOST+"/tafsir_mimpi/userdata/";
global.CONTENTS = {
	"newbie": [
		{
			"name": "Landing Zone",
			"description": "How to better landing zone",
			"image": "landing_zone",
			"contents": [
				{
					"content": "When you enter the game, you will be in the aircraft@that brings you to an island and you will be landed@there.\n\nBut, you should not land in the wrong area@because it could bring some risks.",
					"image": "landing_zone_1"
				},
				{
					"content": "You should look for a safe place for landing@so you won’t be lost.\n\nFor instance, if you@are landed in a crowded area that full of the@other players and you haven’t done the looting,@you will become the other’s target.",
					"image": "landing_zone_2"
				},
				{
					"content": "It's better if you come to a small city to@get a little amount of loot but the place@is rather far from the war zone, so you@will be safer and survive longer.",
					"image": "landing_zone_3"
				}
			]
		},
		{
			"name": "Looting",
			"description": "How to to looting",
			"image": "looting",
			"contents": [
				{
					"content": "After you can land, you must do the loot equipment@as you needed around your position, usually, there@are many essential types of equipment like gun,@helmet, bag, and so on inside the houses.",
					"image": "looting_1"
				},
				{
					"content": "You should close the door when you process the@looting inside the house in order no opponent@can find you.\n\nThe opened door will invite other@enemies to come and find your position.",
					"image": "looting_2"
				},
				{
					"content": "When you are looting the gun, you must know@the gun types such as rifle sniper, DMR,@assault rifle, SMG, shotgun, gun, and melee.@Besides that, there is armour that has a@level to mark its skill to decrease the@damage from other enemies.\n\nLevel 1 armour@can decrease 30% damage, level 2 for decreasing 40% damage, and level 3 for decreasing 55% damage.",
					"image": "looting_3"
				},
				{
					"content": "You also will find the healing and boost item@when you are looting.\n\nHealing item will be@useful to heal your HP, boost item will give@the additional item.",
					"image": "looting_4"
				}
			]
		},
		{
			"name": "Mini Map and Earphone",
			"description": "View mini map and earphone",
			"image": "mini_map",
			"contents": [
				{
					"content": "To displaying your location, the mini-map also@displays opponent locations, enemy fire directions,@and vehicles next to where you are.\n\nThe mini-map@is in the top corner, then you can see the@surroundings, don't forget to use earphones@to find out the sound of footprints from your@opponent.\n\nBy looking at the mini-map while@listening to the sounds around you, you will@know when to hide and when to attack.",
					"image": "mini_map_1",
				}
			]
		},
		{
			"name": "Safe Zone",
			"description": "How to find safe zone",
			"image": "safe_zone",
			"contents": [
				{
					"content": "An area marked by a white circle on the map@in PUBG Mobile is called as Safe Zone, aka@the safe zone, which will shrink over time.@You must always be in the Safe Zone, otherwise,@you will get the tick damage generated by EMP@aka blue circle.\n\nIf the safe zone gets smaller,@the more damage you will receive while you are@still outside the zone, you might die there.@Don't get caught and intercepted by your@opponent when you enter the safe zone!",
					"image": "safe_zone_1"
				}
			]
		}
	],
	"expert": [
		{
			"name": "Survival Zone",
			"description": "How to find survival zone",
			"image": "survival_zone",
			"contents": [
				{
					"content": "To be an expert PUBG player, you need to know@that survival time also holds an impact just@like the hardcore kills.\n\nBased on the assigned@rating from any player said that we need 80%@survival time and 20% kills to get the conqueror.@Then you should be in the top 10 for almost 95%@of the time.",
					"image": "survival_zone_1"
				}
			]
		},
		{
			"name": "Choose the Right Squad",
			"description": "How to choose the right squad",
			"image": "squad",
			"contents": [
				{
					"content": "If you want to achieve the conqueror of your@squad the most important thing is choosing@the right and a good team.\n\nPlayer who choose@the bad option can often draw you the lobby.@Think wise to make a strategic plan.",
					"image": "squad_1"
				}
			]
		},
		{
			"name": "Choose the Right Utilities",
			"description": "How to choose the right utilities",
			"image": "utilities",
			"contents": [
				{
					"content": "Ammunition isn't really that important as you@might think.\n\nWhen trying to encourage conquerors,@it is best to replace some of them with utility@tools such as smoke grenades.\n\nIf you own more@smoke, the longer you can play until the last@zone.",
					"image": "utilities_1",
				}
			]
		},
		{
			"name": "Vehicle",
			"description": "How to choose best vehicle",
			"image": "vehicle",
			"contents": [
				{
					"content": "Riding a vehicle is very important in every@combat situations.\n\nWhen you ride a vehicle,@you will go faster to your destination and@can serve to shift with your squad when it@breaks down.\n\nGet your hand on a vehicle@immediately as you hit the ground.",
					"image": "vehicle_1"
				}
			]
		},
		{
			"name": "Weapon's combination",
			"description": "How to choose weapon's combination",
			"image": "weapon",
			"contents": [
				{
					"content": "Let's try to get the rifles that is the included@as the most powerful weapon in PUBG.\n\nThe best os@AR with different specs like AKM + M416, however@you can replace it with an SMG if you don’t find@any.",
					"image": "weapon_1"
				}
			]
		},
		{
			"name": "Zone Prediction",
			"description": "How to do zone prediction",
			"image": "zone",
			"contents": [
				{
					"content": "The newest update seems to have changed the zone's@behavior a little bit.\n\nBecause of the chase zone@is the first cause of death in this game, it’s@better for you to cut down as much as possible.@While you push to the conqueror, you should try@to stay on the edge of the zone, try to stay until@the fifth zone.\n\nThen, find a place where you can@occupy inside and stay safe until the final battle.",
					"image": "zone_1"
				}
			]
		}
	],
	"advance": [
		{
			"name": "Parachute Method",
			"description": "Use the parachute method",
			"image": "parachute",
			"contents": [
				{
					"content": "To win the early gunfight, you should master this@basic method.\n\nRemember to not landing in a popular@hot-spots where other squads take their drops.\n\nYour@team will be difficult to loot.\n\nSo when you’re 750@meters away from your desired area, drop out from@the ship.\n\nYou will drop faster at the speed of 234 km/h.",
					"image": "parachute_1"
				}
			]
		},
		{
			"name": "Know Your Land Area",
			"description": "How to know your land area",
			"image": "land_area",
			"contents": [
				{
					"content": "You should know the right location to land.@If you’re with your team, land close to your@ally, so if one person gets knocked out, you@can revive them.\n\nIf you’re a solo player, land@in areas you know have proper and good consistent@loots.\n\nTry the ris like Military Base, Casino, or@School to achieve the most amount of high grade@loots.",
					"image": "land_area_1"
				}
			]
		},
		{
			"name": "Know Where Vehicles Spawn",
			"description": "How to know where vehicles spawn",
			"image": "vehicle_spawn",
			"contents": [
				{
					"content": "Knowing where the vehicles spawn is important.@PUBG mobile maps are big, unless you play in@an arcade mode, the circle will become smaller@with time.\n\nIn some instances, you are able to@run in a safe area, but you can’t do it if@you’re 2000 meters away.",
					"image": "vehicle_spawn_1"
				}
			]
		},
		{
			"name": "Perfect Your Setting",
			"description": "How to make your setting perfect",
			"image": "perfect_settings",
			"contents": [
				{
					"content": "To get the best graphic and your game can run@smoothly, perfect your device’s setting.\n\nKeep@your photos or videos in the cloud storage so@you can keep enough space then reduce the memory@usage from the apps.\n\nIf you have played 3-4@games, you should exit out from every app you@have used, restart the device, then open again@PUBG Mobile app.",
					"image": "perfect_settings_1"
				}
			]
		},
		{
			"name": "Never carry an inventory full of unnecessary items!",
			"description": "Don't bring inventory with unnecessary items",
			"image": "inventory",
			"contents": [
				{
					"content": "Bring the necessary item like your suitable@gun for fighting with the opponent in a@certain area.\n\nDon’t make your backpack@full of unnecessary items.\n\nYou should@move quickly after the mission is ended.",
					"image": "inventory_1"
				}
			]
		},
		{
			"name": "Learn How To Use a Gun",
			"description": "How to better use gun",
			"image": "gun",
			"contents": [
				{
					"content": "As an advanced player, you should learn how@to use all of the weapon.\n\nFeel the dynamic@when you fight.Practice every gun in your early@level and don’t be bothered with your level.\n\nIf@you’re trained well with the weapons, you will@be easier to fight against your opponent.",
					"image": "gun_1"
				}
			]
		},
		{
			"name": "Learn About Gyroscope",
			"description": "Learn what gyroscope is",
			"image": "gyroscope",
			"contents": [
				{
					"content": "It is very important to learn about gyroscope.@Learn about gyroscope features and master it@to face your opponent smoothly.\n\nUsually you@will need close to a week to master all of@gyroscope features.",
					"image": "gyroscope_1",
				}
			]
		}
	],
	"pro": [
		{
			"name": "Survival Time",
			"description": "How to better doing survival time",
			"image": "survival_time",
			"contents": [
				{
					"content": "You need to survive until the end of the game@in PUBG.\n\nSurvival time will give the impact@on your ranking point that helps you to reach@the higher tier.\n\nIncrease your survival time@in every game and look at your statistic’s@average time.\n\nKeep it at around 22-25 minutes.",
					"image": "survival_time_1"
				}
			]
		},
		{
			"name": "Importance of Kills",
			"description": "Learn about importance of kills",
			"image": "importance_of_kills",
			"contents": [
				{
					"content": "To help your push rank, you need to increase your@number of kills because it’s important to increase@your ranking points along with your survival time too.",
					"image": "importance_of_kills_1"
				}
			]
		},
		{
			"name": "Get Chicken Dinners As Much As Possible",
			"description": "How to get chicken dinners",
			"image": "chicken_dinner",
			"contents": [
				{
					"content": "Chicken dinners are a great way to get more plus@points in PUBG Mobile.\n\nThe key to this game is@to keep your cool and make good decisions to win@the game.\n\nThen, you can get more wins, and move@up the rankings faster from Crown to Ace.",
					"image": "chicken_dinner_1"
				}
			]
		},
		{
			"name": "Avoid Playing with Random Players",
			"description": "How to avoid playing with random players",
			"image": "random_player",
			"contents": [
				{
					"content": "When you are stuck at Crown level in PUBG Mobile@and want to move up to Ace level, don't play with@random squads.\n\nBecause many players in random squads@may not hear your call, communicating with random@players is very difficult, as they rarely use the@voice chat feature.\n\nBesides that, in most of the@cases you don’t land with these random players.@So, it's better if you play with friends or the@regular squad because you already know their@strengths and weaknesses.",
					"image": "random_player_1"
				}
			]
		},
		{
			"name": "Health Restored",
			"description": "How to make health restored",
			"image": "health_recover",
			"contents": [
				{
					"content": "Health restored amount will give the key role@to provide you more and point in the game.@Therefore, let’s try to collect more first@aid kits and also health boosters.\n\nYou should@take some zone damages in the first three zones@by staying outside the zone then healing yourself.@If you do that, you will receive health restoration@points on every match’s completion.",
					"image": "health_recover_1"
				}
			]
		}
	]
};
global.log = (message) => {
	console.log(message);
};
/*global.BANNER_AD_ID = "ca-app-pub-3950402057146083/5883645909";
global.INTERSTITIAL_AD_ID = "ca-app-pub-3950402057146083/4570564233";
global.NATIVE_AD_ID = "ca-app-pub-3950402057146083/6173621646";*/
/* TEST AD ID */
global.INTERSTITIAL_AD_ID = "ca-app-pub-3940256099942544/1033173712";
global.BANNER_AD_ID = "ca-app-pub-3940256099942544/6300978111";
global.NATIVE_AD_ID = "ca-app-pub-3940256099942544/2247696110";
global.cs_email = "luckynine.cs@gmail.com";
global.DEVELOPER_HOME = "https://play.google.com/store/apps/dev?id=6323058473789380568";
global.PACKAGE_NAME = "com.emz.bukuimpi.tafsirmimpi.kodealam.artimimpi.ramalanangka.sdysgphk.joyoboyo";
global.readString = async (name, defaultValue, callback) => {
	NativeModules.AndroidUtil.readString(name, defaultValue, (value) => {
		if (value == null) {
			callback(defaultValue);
			return;
		}
		callback(value);
	});
};
global.readInt = async (name, defaultValue, callback) => {
	NativeModules.AndroidUtil.readInt(name, defaultValue, (value) => {
		if (value == null) {
			callback(defaultValue);
			return;
		}
		callback(value);
	});
};
global.readBoolean = async (name, defaultValue, callback) => {
	NativeModules.AndroidUtil.readBoolean(name, defaultValue, (value) => {
		if (value == null) {
			callback(defaultValue);
			return;
		}
		callback(value);
	});
};
global.writeString = async (name, value) => {
	NativeModules.AndroidUtil.writeString(name, value);
};
global.writeInt = async (name, value) => {
	NativeModules.AndroidUtil.writeInt(name, value);
};
global.writeBoolean = async (name, value) => {
	NativeModules.AndroidUtil.writeBoolean(name, value);
};
global.uuidv4 = () => {
	return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    	var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    	return v.toString(16);
  	});
};
global.splitByNewline = (str, maxLength) => {
    var buff = "";
    var numOfLines = Math.floor(str.length/maxLength);
    for(var i = 0; i<numOfLines+1; i++) {
        buff += str.substr(i*maxLength, maxLength); if(i !== numOfLines) { buff += "@"; }
    }
    return buff;
}
global.string = {
	app_name: "Tafsir Mimpi",
	text1: "Pilih Kata atau Angka",
	text2: "Angka",
	text3: "Tafsir Mimpi 2A",
	text4: "Tafsir Mimpi 3A",
	text5: "Tafsir Mimpi 4A",
	text6: "Tafsir Mimpi Full",
	text7: "Tentang Aplikasi",
	text8: "Beri 5 Bintang",
	text9: "Kata Kata",
	text10: "Mohon masukkan kata kunci",
	text11: "Pilih tafsir mimpi",
	text12: "Mohon masukkan 2 angka",
	text13: "Mohon masukkan 3 angka",
	text14: "Mohon masukkan 4 angka",
	settings: "Pengaturan",
	notification: "Notifikasi",
	information: "Informasi",
	share: "Bagikan",
	loading: "Memuat...",
	others: "Others"
};
global.show = (message) => {
	NativeModules.AndroidUtil.show(message);
};
global.showInterstitialAd = () => {
	AdMobInterstitial.setAdUnitID(INTERSTITIAL_AD_ID);
	AdMobInterstitial.setTestDevices([AdMobInterstitial.simulatorId]);
	AdMobInterstitial.requestAd().then(() => AdMobInterstitial.showAd());
};
